
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author user
 */

public class LoginAccount extends javax.swing.JFrame {

    /**
     * Creates new form LoginAccount
     */
    public LoginAccount() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        LoginBTTN = new javax.swing.JButton();
        cancelBTTN = new javax.swing.JButton();
        unTF = new javax.swing.JTextField();
        pwTF = new javax.swing.JPasswordField();
        pwShow = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(330, 360));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Bodoni MT", 1, 14)); // NOI18N
        jLabel2.setText("Username:");
        jLabel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 75, 25));

        jLabel3.setFont(new java.awt.Font("Bodoni MT", 1, 14)); // NOI18N
        jLabel3.setText("Password:");
        jLabel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 75, 25));

        LoginBTTN.setText("Login");
        LoginBTTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginBTTNActionPerformed(evt);
            }
        });
        getContentPane().add(LoginBTTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, -1, 30));

        cancelBTTN.setText("Cancel");
        cancelBTTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBTTNActionPerformed(evt);
            }
        });
        getContentPane().add(cancelBTTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, 100, 30));

        unTF.setFont(new java.awt.Font("Bodoni MT", 0, 14)); // NOI18N
        unTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unTFActionPerformed(evt);
            }
        });
        getContentPane().add(unTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 110, 25));

        pwTF.setFont(new java.awt.Font("Bodoni MT", 1, 14)); // NOI18N
        pwTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwTFActionPerformed(evt);
            }
        });
        getContentPane().add(pwTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 110, 25));

        pwShow.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        pwShow.setText("Show Password");
        pwShow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwShowActionPerformed(evt);
            }
        });
        getContentPane().add(pwShow, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Desktop\\haha\\SchoolBoi\\src\\YsmdCUB.jpg")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-750, 0, 1080, 360));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void unTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unTFActionPerformed

    private void cancelBTTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBTTNActionPerformed
       System.exit(0);
    }//GEN-LAST:event_cancelBTTNActionPerformed

    private void LoginBTTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginBTTNActionPerformed
        
        if (unTF.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Please fill out your Username");
        }
        else if(pwTF.getText().equals("")){
        JOptionPane.showMessageDialog(null,"Please fill out your Password");
        }
        else if(unTF.getText().contains("admin")&& pwTF.getText().contains("khosner23")){
                JOptionPane.showMessageDialog(null, "Successully Login");
                NewJFrame log = new NewJFrame();
        log.setVisible(true);
                }
        else{
            JOptionPane.showMessageDialog(null, "Wrong username or password!","Message",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_LoginBTTNActionPerformed

    private void pwTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pwTFActionPerformed

    private void pwShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwShowActionPerformed
        if(pwShow.isSelected()){
            pwTF.setEchoChar((char)0);
        }
        else{
            pwTF.setEchoChar('*');
        }
    }//GEN-LAST:event_pwShowActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginAccount().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LoginBTTN;
    private javax.swing.JButton cancelBTTN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JCheckBox pwShow;
    private javax.swing.JPasswordField pwTF;
    private javax.swing.JTextField unTF;
    // End of variables declaration//GEN-END:variables
}
