
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.io.RandomAccessFile;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import jdk.nashorn.internal.scripts.JO;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author user
 */
public class NewJFrame extends javax.swing.JFrame {

    File file = new File("data.txt"); 


    
    public void createNewFunction(){
        if (!file.exists()){
            try {
                file.createNewFile();
            } catch (IOException ex) {
                Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
        
    int line = 0;
    public void numLine(){
        line = 0;
        try {
            RandomAccessFile rndm = new RandomAccessFile(file,"rw");
            while(rndm.readLine()!=null){
                line++;
            }
            rndm.close(); 
        } catch (FileNotFoundException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    
    public void readDataFunction(){
        String title = "Name,Age,School ID,Gender,Course";
        try {
            BufferedReader reader = new BufferedReader(new FileReader(file));
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.getDataVector().removeAllElements();
            model.fireTableDataChanged();
            String[] splitTitle = title.trim().split(",");
            model.setColumnIdentifiers(splitTitle);
            
            Object[] object = reader.lines().toArray();
            
            for(int i = 0; i<object.length; i++){
                String[] dataSplit = object[i].toString().trim().split(",");
                model.addRow(dataSplit);
            }
           //reader.close();
                
            
        } catch (FileNotFoundException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    } 
    
            
    public void createData(){
        numLine();
        try {
            RandomAccessFile rndm = new RandomAccessFile(file,"rw");
            for(int i = 1; i<=line; i++){
                rndm.readLine();
            } 
            
            rndm.writeBytes(nameTF.getText()+","+ageTF.getText()+","+idTF.getText()+","+genderTF.getText()+","+courseTF.getText());
            rndm.writeBytes(System.lineSeparator());
            rndm.close();
            nameTF.setText("");
            ageTF.setText("");
            idTF.setText("");
            genderTF.setText("");
            courseTF.setText("");
        } catch (FileNotFoundException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void DeleteData(){
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        
        if(jTable1.getSelectedRow()== 0) {
            model.removeRow(jTable1.getSelectedRow());
        }else{
            if(jTable1.getRowCount()==0){
                JOptionPane.showMessageDialog(this, "Table is empty.");
               
            }else{
                JOptionPane.showMessageDialog(this, "Please select Single row for Delete.");
            }
            
        }
    }
  //  public void DeleteFile(){
    //   File fileObj = new File("C:\\Users\\user\\Desktop\\haha\\SchoolBoi.txt");
      //  if (fileObj.exists())
       // {
         //   if (fileObj.delete())
          //  {
           //     System.out.println("File/ Folder Deleted Successfully");
        //    } else {
          //      System.out.println("File/ Folder Could not be Deleted");
          //  } 
       // }
   // }
    
       public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        nameTF = new javax.swing.JTextField();
        ageTF = new javax.swing.JTextField();
        idTF = new javax.swing.JTextField();
        genderTF = new javax.swing.JTextField();
        courseTF = new javax.swing.JTextField();
        createBTTN = new javax.swing.JButton();
        readBTTN = new javax.swing.JButton();
        updateBTTN = new javax.swing.JButton();
        deleteBTTN = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Name:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 100, 20));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel2.setText("Information System");
        jLabel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(102, 102, 102)));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 230, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Age:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 70, 20));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("School ID:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 90, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Gender:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 80, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Course:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 80, -1));

        nameTF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nameTF.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(nameTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 150, -1));

        ageTF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ageTF.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(ageTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 150, -1));

        idTF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        idTF.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(idTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 150, -1));

        genderTF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        genderTF.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(genderTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 150, -1));

        courseTF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        courseTF.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(courseTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, 150, -1));

        createBTTN.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        createBTTN.setText("Create");
        createBTTN.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        createBTTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createBTTNActionPerformed(evt);
            }
        });
        getContentPane().add(createBTTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 260, -1, -1));

        readBTTN.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        readBTTN.setText("Read");
        readBTTN.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        readBTTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                readBTTNActionPerformed(evt);
            }
        });
        getContentPane().add(readBTTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(473, 260, 80, -1));

        updateBTTN.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        updateBTTN.setText("Update");
        updateBTTN.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        updateBTTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBTTNActionPerformed(evt);
            }
        });
        getContentPane().add(updateBTTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 260, 80, -1));

        deleteBTTN.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        deleteBTTN.setText("Delete");
        deleteBTTN.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        deleteBTTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBTTNActionPerformed(evt);
            }
        });
        getContentPane().add(deleteBTTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 260, 80, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Age", "School ID", "Gender", "Course"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setGridColor(new java.awt.Color(51, 153, 255));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 30, -1, 210));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/YsmdCUB.jpg"))); // NOI18N
        jLabel7.setText("jLabel7");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(-680, -230, -1, 1270));

        setSize(new java.awt.Dimension(866, 359));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void updateBTTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBTTNActionPerformed
     //  updateData();
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        
        int selectRowIndex = jTable1.getSelectedRow();
        
        String name = model.getValueAt(selectRowIndex, 0).toString();
       String age = model.getValueAt(selectRowIndex, 0).toString();
        String id = model.getValueAt(selectRowIndex, 0).toString();
        String gender = model.getValueAt(selectRowIndex, 0).toString();
        String course = model.getValueAt(selectRowIndex, 0).toString();
       
       String nName = JOptionPane.showInputDialog(null,"Enter the new name",name);
        String nAge = JOptionPane.showInputDialog(null,"Enter the new age",age);
        String nID = JOptionPane.showInputDialog(null,"Enter the new ID",id);
        String nGender = JOptionPane.showInputDialog(null,"Enter the new Gender",gender);
        String nCourse = JOptionPane.showInputDialog(null,"Enter the new Course",course);
        
       model.setValueAt(nName, selectRowIndex, 0);
        model.setValueAt(nAge, selectRowIndex, 1);
        model.setValueAt(nID, selectRowIndex, 2);
        model.setValueAt(nGender, selectRowIndex, 3);
        model.setValueAt(nCourse, selectRowIndex, 4);


        
        
        
    }//GEN-LAST:event_updateBTTNActionPerformed

    private void deleteBTTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBTTNActionPerformed
      DeleteData();
     // DeleteFile();
       //createNewFunction();
      // numLine();
      
    }//GEN-LAST:event_deleteBTTNActionPerformed

    private void createBTTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createBTTNActionPerformed
        createNewFunction();
        createData();
        numLine();
    }//GEN-LAST:event_createBTTNActionPerformed

    private void readBTTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_readBTTNActionPerformed
        readDataFunction();
    }//GEN-LAST:event_readBTTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ageTF;
    private javax.swing.JTextField courseTF;
    private javax.swing.JButton createBTTN;
    private javax.swing.JButton deleteBTTN;
    private javax.swing.JTextField genderTF;
    private javax.swing.JTextField idTF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField nameTF;
    private javax.swing.JButton readBTTN;
    private javax.swing.JButton updateBTTN;
    // End of variables declaration//GEN-END:variables
}
